---
- include: install.yml
  become: yes
  when: action is undefined

- include: configure.yml
  become: yes
  when: action is undefined

- include: vm_loop.yml
  with_items: "{{ azure_hosts }}"
  become: yes
  become_user: "{{ terraform_user }}"
  when: action is undefined

- include: dns_loop.yml
  with_dict: "{{ reference_sites }}"
  become: yes
  become_user: "{{ terraform_user }}"
  when: action is undefined

- include: destroy.yml
  when: (action is defined and action == "stop")
